[package]
name = "wacp-sdk"
description = "WACP — Rust agent SDK"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
wacp-types = { path = "../wacp-types" }
wacp-transport = { path = "../wacp-transport" }
tokio = { workspace = true }
tonic = { workspace = true }
thiserror = { workspace = true }
futures = "0.3"

[dev-dependencies]
tokio = { workspace = true }
