[package]
name = "console-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
wacp-taxonomy = { workspace = true }
wacp-types = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
