# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: primitives.proto, agent.proto, highway.proto, coordinator.proto, taxonomy.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import AsyncGenerator, List, Optional

import betterproto
import grpclib


class SignalType(betterproto.Enum):
    SIGNAL_TYPE_UNSPECIFIED = 0
    SIGNAL_TYPE_READY = 1
    SIGNAL_TYPE_STARTED = 2
    SIGNAL_TYPE_BLOCKED = 3
    SIGNAL_TYPE_CHECKPOINT = 4
    SIGNAL_TYPE_COMPLETE = 5
    SIGNAL_TYPE_FAILED = 6
    SIGNAL_TYPE_INTEGRATE = 7
    SIGNAL_TYPE_ACKNOWLEDGED = 8
    SIGNAL_TYPE_ESCALATION = 9
    SIGNAL_TYPE_SUSPEND = 10
    SIGNAL_TYPE_MIGRATE = 11


class WorkspaceState(betterproto.Enum):
    WORKSPACE_STATE_UNSPECIFIED = 0
    WORKSPACE_STATE_IDLE = 1
    WORKSPACE_STATE_ACTIVE = 2
    WORKSPACE_STATE_BLOCKED = 3
    WORKSPACE_STATE_SUSPENDED = 4
    WORKSPACE_STATE_MIGRATING = 5
    WORKSPACE_STATE_INTEGRATING = 6
    WORKSPACE_STATE_CONFLICTED = 7
    WORKSPACE_STATE_CLOSED = 8
    WORKSPACE_STATE_FAILED = 9


class EnvelopeState(betterproto.Enum):
    ENVELOPE_STATE_UNSPECIFIED = 0
    ENVELOPE_STATE_CREATED = 1
    ENVELOPE_STATE_VALIDATED = 2
    ENVELOPE_STATE_DELIVERED = 3
    ENVELOPE_STATE_ACKNOWLEDGED = 4
    ENVELOPE_STATE_REJECTED = 5


class TaskStatus(betterproto.Enum):
    TASK_STATUS_UNSPECIFIED = 0
    TASK_STATUS_DRAFT = 1
    TASK_STATUS_PENDING = 2
    TASK_STATUS_ASSIGNED = 3
    TASK_STATUS_IN_PROGRESS = 4
    TASK_STATUS_COMPLETED = 5
    TASK_STATUS_FAILED = 6
    TASK_STATUS_INTEGRATED = 7
    TASK_STATUS_CANCELLED = 8


class CheckpointStatus(betterproto.Enum):
    CHECKPOINT_STATUS_UNSPECIFIED = 0
    CHECKPOINT_STATUS_PROVISIONAL = 1
    CHECKPOINT_STATUS_FINAL = 2


class Confidence(betterproto.Enum):
    CONFIDENCE_UNSPECIFIED = 0
    CONFIDENCE_HIGH = 1
    CONFIDENCE_MEDIUM = 2
    CONFIDENCE_LOW = 3


class EnvelopePriority(betterproto.Enum):
    ENVELOPE_PRIORITY_UNSPECIFIED = 0
    ENVELOPE_PRIORITY_NORMAL = 1
    ENVELOPE_PRIORITY_URGENT = 2
    ENVELOPE_PRIORITY_BLOCKING = 3


class EnvelopeOrigin(betterproto.Enum):
    ENVELOPE_ORIGIN_UNSPECIFIED = 0
    ENVELOPE_ORIGIN_AGENT = 1
    ENVELOPE_ORIGIN_HUMAN = 2


class ErrorCategory(betterproto.Enum):
    ERROR_CATEGORY_UNSPECIFIED = 0
    ERROR_CATEGORY_PERMISSION_DENIED = 1
    ERROR_CATEGORY_ILLEGAL_TRANSITION = 2
    ERROR_CATEGORY_VALIDATION_FAILED = 3
    ERROR_CATEGORY_BUDGET_EXCEEDED = 4
    ERROR_CATEGORY_TIMEOUT = 5
    ERROR_CATEGORY_NOT_FOUND = 6
    ERROR_CATEGORY_DELIVERY_FAILED = 7
    ERROR_CATEGORY_INTERNAL = 8


class GateType(betterproto.Enum):
    GATE_TYPE_UNSPECIFIED = 0
    GATE_TYPE_TASK_APPROVAL = 1
    GATE_TYPE_WORKSPACE_CREATE = 2
    GATE_TYPE_ENVELOPE_DELIVERY = 3
    GATE_TYPE_INTEGRATION = 4
    GATE_TYPE_CONFLICT_RESOLUTION = 5
    GATE_TYPE_WORKSPACE_ABORT = 6
    GATE_TYPE_CHECKPOINT_APPROVAL = 7


class GateDecision(betterproto.Enum):
    GATE_DECISION_UNSPECIFIED = 0
    GATE_DECISION_APPROVE = 1
    GATE_DECISION_REJECT = 2
    GATE_DECISION_MODIFY = 3


@dataclass
class Timestamp(betterproto.Message):
    physical_us: int = betterproto.uint64_field(1)
    logical: int = betterproto.uint32_field(2)


@dataclass
class Envelope(betterproto.Message):
    id: str = betterproto.string_field(1)
    from_workspace: str = betterproto.string_field(2)
    to_workspace: str = betterproto.string_field(3)
    type: str = betterproto.string_field(4)
    payload: bytes = betterproto.bytes_field(5)
    in_reply_to: str = betterproto.string_field(6)
    timestamp: "Timestamp" = betterproto.message_field(7)
    priority: "EnvelopePriority" = betterproto.enum_field(8)
    origin: "EnvelopeOrigin" = betterproto.enum_field(9)


@dataclass
class Signal(betterproto.Message):
    type: "SignalType" = betterproto.enum_field(1)
    workspace_id: str = betterproto.string_field(2)
    timestamp: "Timestamp" = betterproto.message_field(3)
    reason: str = betterproto.string_field(4)
    context: bytes = betterproto.bytes_field(5)


@dataclass
class Checkpoint(betterproto.Message):
    id: str = betterproto.string_field(1)
    workspace_id: str = betterproto.string_field(2)
    type: str = betterproto.string_field(3)
    payload: bytes = betterproto.bytes_field(4)
    content_hash: str = betterproto.string_field(5)
    intent: str = betterproto.string_field(6)
    parent_checkpoint: str = betterproto.string_field(7)
    status: "CheckpointStatus" = betterproto.enum_field(8)
    confidence: "Confidence" = betterproto.enum_field(9)
    timestamp: "Timestamp" = betterproto.message_field(10)
    resource_usage: "ResourceUsage" = betterproto.message_field(11)


@dataclass
class Task(betterproto.Message):
    id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    depends_on: List[str] = betterproto.string_field(4)
    parent_task: str = betterproto.string_field(5)
    status: "TaskStatus" = betterproto.enum_field(6)
    workspace_ref: str = betterproto.string_field(7)
    workspace_history: List[str] = betterproto.string_field(8)
    checkpoint_ref: str = betterproto.string_field(9)


@dataclass
class TrailEntry(betterproto.Message):
    id: str = betterproto.string_field(1)
    timestamp: "Timestamp" = betterproto.message_field(2)
    workspace_id: str = betterproto.string_field(3)
    actor: str = betterproto.string_field(4)
    event_type: str = betterproto.string_field(5)
    body: bytes = betterproto.bytes_field(6)
    sequence_number: int = betterproto.uint64_field(7)
    chain_hash: bytes = betterproto.bytes_field(8)


@dataclass
class ResourceUsage(betterproto.Message):
    tokens: int = betterproto.uint64_field(1)
    wall_time_ms: int = betterproto.uint64_field(2)
    storage_bytes: int = betterproto.uint64_field(3)
    network_bytes: int = betterproto.uint64_field(4)
    cost_micros: int = betterproto.uint64_field(5)


@dataclass
class ResourceBudget(betterproto.Message):
    max_tokens: int = betterproto.uint64_field(1)
    max_wall_time_ms: int = betterproto.uint64_field(2)
    max_storage_bytes: int = betterproto.uint64_field(3)
    max_network_bytes: int = betterproto.uint64_field(4)
    max_cost_micros: int = betterproto.uint64_field(5)
    warning_threshold: float = betterproto.float_field(6)


@dataclass
class QueryTrailResponse(betterproto.Message):
    entries: List["TrailEntry"] = betterproto.message_field(1)
    has_more: bool = betterproto.bool_field(2)
    client_request_id: str = betterproto.string_field(3)


@dataclass
class ProtocolError(betterproto.Message):
    category: "ErrorCategory" = betterproto.enum_field(1)
    rule: str = betterproto.string_field(2)
    message: str = betterproto.string_field(3)
    request_id: str = betterproto.string_field(4)


@dataclass
class Command(betterproto.Message):
    feedback: "Envelope" = betterproto.message_field(1, group="command")
    visibility_grant: "VisibilityGrant" = betterproto.message_field(2, group="command")
    graceful_termination: "GracefulTermination" = betterproto.message_field(
        3, group="command"
    )
    budget_update: "BudgetUpdate" = betterproto.message_field(4, group="command")


@dataclass
class VisibilityGrant(betterproto.Message):
    resource_ids: List[str] = betterproto.string_field(1)


@dataclass
class GracefulTermination(betterproto.Message):
    grace_period_ms: int = betterproto.uint64_field(1)


@dataclass
class BudgetUpdate(betterproto.Message):
    new_budget: "ResourceBudget" = betterproto.message_field(1)


@dataclass
class BindRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    auth_token: str = betterproto.string_field(2)
    client_request_id: str = betterproto.string_field(3)


@dataclass
class BindResponse(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    state: "WorkspaceState" = betterproto.enum_field(2)
    role: str = betterproto.string_field(3)
    directive: "Envelope" = betterproto.message_field(4)
    context: bytes = betterproto.bytes_field(5)
    visibility: List[str] = betterproto.string_field(6)
    authority: List[str] = betterproto.string_field(7)
    budget: "ResourceBudget" = betterproto.message_field(8)


@dataclass
class SendEnvelopeRequest(betterproto.Message):
    to_workspace: str = betterproto.string_field(1)
    type: str = betterproto.string_field(2)
    payload: bytes = betterproto.bytes_field(3)
    in_reply_to: str = betterproto.string_field(4)
    priority: "EnvelopePriority" = betterproto.enum_field(5)
    client_request_id: str = betterproto.string_field(6)


@dataclass
class SendEnvelopeResponse(betterproto.Message):
    envelope_id: str = betterproto.string_field(1)
    timestamp: "Timestamp" = betterproto.message_field(2)
    client_request_id: str = betterproto.string_field(3)


@dataclass
class EmitSignalRequest(betterproto.Message):
    type: "SignalType" = betterproto.enum_field(1)
    reason: str = betterproto.string_field(2)
    context: bytes = betterproto.bytes_field(3)
    client_request_id: str = betterproto.string_field(4)


@dataclass
class EmitSignalResponse(betterproto.Message):
    timestamp: "Timestamp" = betterproto.message_field(1)
    client_request_id: str = betterproto.string_field(2)


@dataclass
class CreateCheckpointRequest(betterproto.Message):
    type: str = betterproto.string_field(1)
    payload: bytes = betterproto.bytes_field(2)
    intent: str = betterproto.string_field(3)
    status: "CheckpointStatus" = betterproto.enum_field(4)
    confidence: "Confidence" = betterproto.enum_field(5)
    resource_usage: "ResourceUsage" = betterproto.message_field(6)
    client_request_id: str = betterproto.string_field(7)


@dataclass
class CreateCheckpointResponse(betterproto.Message):
    checkpoint_id: str = betterproto.string_field(1)
    content_hash: str = betterproto.string_field(2)
    timestamp: "Timestamp" = betterproto.message_field(3)
    client_request_id: str = betterproto.string_field(4)


@dataclass
class QueryTrailRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    event_type: str = betterproto.string_field(2)
    from_: "Timestamp" = betterproto.message_field(3)
    to: "Timestamp" = betterproto.message_field(4)
    limit: int = betterproto.uint32_field(5)
    client_request_id: str = betterproto.string_field(6)


@dataclass
class ReadResourceRequest(betterproto.Message):
    resource_id: str = betterproto.string_field(1)
    client_request_id: str = betterproto.string_field(2)


@dataclass
class ReadResourceResponse(betterproto.Message):
    content: bytes = betterproto.bytes_field(1)
    client_request_id: str = betterproto.string_field(2)


@dataclass
class ReceiveEnvelopesRequest(betterproto.Message):
    pass


@dataclass
class ReceiveCommandsRequest(betterproto.Message):
    pass


@dataclass
class AuthenticateRequest(betterproto.Message):
    auth_token: str = betterproto.string_field(1)


@dataclass
class AuthenticateResponse(betterproto.Message):
    user_id: str = betterproto.string_field(1)
    capabilities: List[str] = betterproto.string_field(2)


@dataclass
class InjectEnvelopeRequest(betterproto.Message):
    to_workspace: str = betterproto.string_field(1)
    type: str = betterproto.string_field(2)
    payload: bytes = betterproto.bytes_field(3)
    priority: "EnvelopePriority" = betterproto.enum_field(4)
    client_request_id: str = betterproto.string_field(5)


@dataclass
class InjectEnvelopeResponse(betterproto.Message):
    envelope_id: str = betterproto.string_field(1)
    timestamp: "Timestamp" = betterproto.message_field(2)
    client_request_id: str = betterproto.string_field(3)


@dataclass
class GateEvent(betterproto.Message):
    gate_id: str = betterproto.string_field(1)
    type: "GateType" = betterproto.enum_field(2)
    subject: bytes = betterproto.bytes_field(3)
    workspace_id: str = betterproto.string_field(4)
    task_id: str = betterproto.string_field(5)
    timeout_ms: int = betterproto.uint64_field(6)
    fallback_action: str = betterproto.string_field(7)
    created_at: "Timestamp" = betterproto.message_field(8)


@dataclass
class GateResponse(betterproto.Message):
    gate_id: str = betterproto.string_field(1)
    decision: "GateDecision" = betterproto.enum_field(2)
    modifications: bytes = betterproto.bytes_field(3)
    client_request_id: str = betterproto.string_field(4)


@dataclass
class GateResponseAck(betterproto.Message):
    gate_id: str = betterproto.string_field(1)
    applied: bool = betterproto.bool_field(2)
    client_request_id: str = betterproto.string_field(3)


@dataclass
class EscalationEvent(betterproto.Message):
    escalation_id: str = betterproto.string_field(1)
    workspace_id: str = betterproto.string_field(2)
    owner: str = betterproto.string_field(3)
    context: bytes = betterproto.bytes_field(4)
    created_at: "Timestamp" = betterproto.message_field(5)


@dataclass
class EscalationResponse(betterproto.Message):
    escalation_id: str = betterproto.string_field(1)
    feedback: "Envelope" = betterproto.message_field(2, group="action")
    abort: bool = betterproto.bool_field(3, group="action")
    delegate_to_coordinator: bool = betterproto.bool_field(4, group="action")
    client_request_id: str = betterproto.string_field(5)


@dataclass
class EscalationResponseAck(betterproto.Message):
    escalation_id: str = betterproto.string_field(1)
    applied: bool = betterproto.bool_field(2)
    client_request_id: str = betterproto.string_field(3)


@dataclass
class HighwayQueryTrailRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    event_type: str = betterproto.string_field(2)
    actor: str = betterproto.string_field(3)
    from_: "Timestamp" = betterproto.message_field(4)
    to: "Timestamp" = betterproto.message_field(5)
    limit: int = betterproto.uint32_field(6)
    client_request_id: str = betterproto.string_field(7)


@dataclass
class GetWorkspaceRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)


@dataclass
class WorkspaceView(betterproto.Message):
    id: str = betterproto.string_field(1)
    state: "WorkspaceState" = betterproto.enum_field(2)
    role: str = betterproto.string_field(3)
    parent: str = betterproto.string_field(4)
    owner: str = betterproto.string_field(5)
    originator: str = betterproto.string_field(6)
    task_id: str = betterproto.string_field(7)
    current_usage: "ResourceUsage" = betterproto.message_field(8)
    budget: "ResourceBudget" = betterproto.message_field(9)
    checkpoint_count: int = betterproto.uint32_field(10)
    created_at: "Timestamp" = betterproto.message_field(11)
    last_activity: "Timestamp" = betterproto.message_field(12)


@dataclass
class GetTaskGraphRequest(betterproto.Message):
    pass


@dataclass
class TaskGraphView(betterproto.Message):
    tasks: List["Task"] = betterproto.message_field(1)


@dataclass
class GetCheckpointRequest(betterproto.Message):
    checkpoint_id: str = betterproto.string_field(1)


@dataclass
class CheckpointView(betterproto.Message):
    metadata: "Checkpoint" = betterproto.message_field(1)
    payload: bytes = betterproto.bytes_field(2)


@dataclass
class StreamTrailRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    event_type: str = betterproto.string_field(2)
    from_beginning: bool = betterproto.bool_field(3)


@dataclass
class StreamGatesRequest(betterproto.Message):
    pass


@dataclass
class StreamEscalationsRequest(betterproto.Message):
    user_id: str = betterproto.string_field(1)


@dataclass
class StreamWorkspaceChangesRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)


@dataclass
class WorkspaceStateChange(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    previous: "WorkspaceState" = betterproto.enum_field(2)
    current: "WorkspaceState" = betterproto.enum_field(3)
    trigger: str = betterproto.string_field(4)
    timestamp: "Timestamp" = betterproto.message_field(5)


@dataclass
class SubmitGoalRequest(betterproto.Message):
    description: str = betterproto.string_field(1)
    context: bytes = betterproto.bytes_field(2)
    client_request_id: str = betterproto.string_field(3)


@dataclass
class SubmitGoalResponse(betterproto.Message):
    goal_id: str = betterproto.string_field(1)
    root_workspace_id: str = betterproto.string_field(2)


@dataclass
class TaskDefinition(betterproto.Message):
    name: str = betterproto.string_field(1)
    description: str = betterproto.string_field(2)
    depends_on: List[str] = betterproto.string_field(3)
    role: str = betterproto.string_field(4)
    directive_payload: bytes = betterproto.bytes_field(5)
    tools: List[str] = betterproto.string_field(6)


@dataclass
class DecomposeRequest(betterproto.Message):
    tasks: List["TaskDefinition"] = betterproto.message_field(1)
    client_request_id: str = betterproto.string_field(2)


@dataclass
class DecomposeResponse(betterproto.Message):
    task_ids: List[str] = betterproto.string_field(1)


@dataclass
class GetReadyTasksRequest(betterproto.Message):
    client_request_id: str = betterproto.string_field(1)


@dataclass
class GetReadyTasksResponse(betterproto.Message):
    tasks: List["TaskView"] = betterproto.message_field(1)


@dataclass
class TaskView(betterproto.Message):
    task_id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    status: "TaskStatus" = betterproto.enum_field(4)
    assigned_workspace: str = betterproto.string_field(5)
    depends_on: List[str] = betterproto.string_field(6)


@dataclass
class CancelTaskRequest(betterproto.Message):
    task_id: str = betterproto.string_field(1)
    reason: str = betterproto.string_field(2)
    client_request_id: str = betterproto.string_field(3)


@dataclass
class CancelTaskResponse(betterproto.Message):
    pass


@dataclass
class DispatchRequest(betterproto.Message):
    task_id: str = betterproto.string_field(1)
    role: str = betterproto.string_field(2)
    directive_payload: bytes = betterproto.bytes_field(3)
    tools: List[str] = betterproto.string_field(4)
    budget: "ResourceBudget" = betterproto.message_field(5)
    client_request_id: str = betterproto.string_field(6)


@dataclass
class DispatchResponse(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    task_id: str = betterproto.string_field(2)


@dataclass
class AbortWorkspaceRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    reason: str = betterproto.string_field(2)
    client_request_id: str = betterproto.string_field(3)


@dataclass
class AbortWorkspaceResponse(betterproto.Message):
    pass


@dataclass
class SuspendWorkspaceRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    client_request_id: str = betterproto.string_field(2)


@dataclass
class SuspendWorkspaceResponse(betterproto.Message):
    pass


@dataclass
class ResumeWorkspaceRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    client_request_id: str = betterproto.string_field(2)


@dataclass
class ResumeWorkspaceResponse(betterproto.Message):
    pass


@dataclass
class SendDirectiveRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    payload: bytes = betterproto.bytes_field(2)
    client_request_id: str = betterproto.string_field(3)


@dataclass
class SendDirectiveResponse(betterproto.Message):
    envelope_id: str = betterproto.string_field(1)


@dataclass
class SendFeedbackRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    payload: bytes = betterproto.bytes_field(2)
    in_reply_to: str = betterproto.string_field(3)
    client_request_id: str = betterproto.string_field(4)


@dataclass
class SendFeedbackResponse(betterproto.Message):
    envelope_id: str = betterproto.string_field(1)


@dataclass
class TriggerIntegrationRequest(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    client_request_id: str = betterproto.string_field(2)


@dataclass
class TriggerIntegrationResponse(betterproto.Message):
    result: str = betterproto.string_field(1)
    detail: str = betterproto.string_field(2)


@dataclass
class GetAllocatableRequest(betterproto.Message):
    client_request_id: str = betterproto.string_field(1)


@dataclass
class GetAllocatableResponse(betterproto.Message):
    remaining: "ResourceBudget" = betterproto.message_field(1)


@dataclass
class StreamSignalsRequest(betterproto.Message):
    workspace_filter: str = betterproto.string_field(1)
    signal_type_filter: str = betterproto.string_field(2)


@dataclass
class SignalEvent(betterproto.Message):
    workspace_id: str = betterproto.string_field(1)
    signal_type: "SignalType" = betterproto.enum_field(2)
    reason: str = betterproto.string_field(3)
    context: bytes = betterproto.bytes_field(4)
    timestamp: int = betterproto.uint64_field(5)


@dataclass
class TaxonomyDefinition(betterproto.Message):
    id: str = betterproto.string_field(1)
    version: str = betterproto.string_field(2)
    protocol_version: str = betterproto.string_field(3)
    roles: List["RoleDefinition"] = betterproto.message_field(4)
    envelope_types: List["EnvelopeTypeDefinition"] = betterproto.message_field(5)
    checkpoint_types: List["CheckpointTypeDefinition"] = betterproto.message_field(6)


@dataclass
class RoleDefinition(betterproto.Message):
    name: str = betterproto.string_field(1)
    extends: str = betterproto.string_field(2)
    add_capabilities: List[str] = betterproto.string_field(3)
    remove_capabilities: List[str] = betterproto.string_field(4)


@dataclass
class EnvelopeTypeDefinition(betterproto.Message):
    name: str = betterproto.string_field(1)
    sender_roles: List[str] = betterproto.string_field(2)
    receiver_roles: List[str] = betterproto.string_field(3)


@dataclass
class CheckpointTypeDefinition(betterproto.Message):
    name: str = betterproto.string_field(1)
    allowed_roles: List[str] = betterproto.string_field(2)


class AgentServiceStub(betterproto.ServiceStub):
    """Agent-facing gRPC service. One connection per workspace."""

    async def bind(
        self,
        *,
        workspace_id: str = "",
        auth_token: str = "",
        client_request_id: str = "",
    ) -> BindResponse:
        """Bind to a workspace. Called once after connection."""

        request = BindRequest()
        request.workspace_id = workspace_id
        request.auth_token = auth_token
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.AgentService/Bind",
            request,
            BindResponse,
        )

    async def send_envelope(
        self,
        *,
        to_workspace: str = "",
        type: str = "",
        payload: bytes = b"",
        in_reply_to: str = "",
        priority: "EnvelopePriority" = 0,
        client_request_id: str = "",
    ) -> SendEnvelopeResponse:
        """Send an envelope to another workspace."""

        request = SendEnvelopeRequest()
        request.to_workspace = to_workspace
        request.type = type
        request.payload = payload
        request.in_reply_to = in_reply_to
        request.priority = priority
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.AgentService/SendEnvelope",
            request,
            SendEnvelopeResponse,
        )

    async def emit_signal(
        self,
        *,
        type: "SignalType" = 0,
        reason: str = "",
        context: bytes = b"",
        client_request_id: str = "",
    ) -> EmitSignalResponse:
        """Emit a signal declaring a state change."""

        request = EmitSignalRequest()
        request.type = type
        request.reason = reason
        request.context = context
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.AgentService/EmitSignal",
            request,
            EmitSignalResponse,
        )

    async def create_checkpoint(
        self,
        *,
        type: str = "",
        payload: bytes = b"",
        intent: str = "",
        status: "CheckpointStatus" = 0,
        confidence: "Confidence" = 0,
        resource_usage: Optional["ResourceUsage"] = None,
        client_request_id: str = "",
    ) -> CreateCheckpointResponse:
        """Create a checkpoint recording progress."""

        request = CreateCheckpointRequest()
        request.type = type
        request.payload = payload
        request.intent = intent
        request.status = status
        request.confidence = confidence
        if resource_usage is not None:
            request.resource_usage = resource_usage
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.AgentService/CreateCheckpoint",
            request,
            CreateCheckpointResponse,
        )

    async def query_trail(
        self,
        *,
        workspace_id: str = "",
        event_type: str = "",
        from_: Optional["Timestamp"] = None,
        to: Optional["Timestamp"] = None,
        limit: int = 0,
        client_request_id: str = "",
    ) -> QueryTrailResponse:
        """Query the local trail."""

        request = QueryTrailRequest()
        request.workspace_id = workspace_id
        request.event_type = event_type
        if from_ is not None:
            request.from_ = from_
        if to is not None:
            request.to = to
        request.limit = limit
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.AgentService/QueryTrail",
            request,
            QueryTrailResponse,
        )

    async def read_resource(
        self, *, resource_id: str = "", client_request_id: str = ""
    ) -> ReadResourceResponse:
        """Read a resource within the visibility set."""

        request = ReadResourceRequest()
        request.resource_id = resource_id
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.AgentService/ReadResource",
            request,
            ReadResourceResponse,
        )

    async def receive_envelopes(self) -> AsyncGenerator[Envelope, None]:
        """Receive envelopes as they arrive in the inbox."""

        request = ReceiveEnvelopesRequest()

        async for response in self._unary_stream(
            "/wacp.v1.AgentService/ReceiveEnvelopes",
            request,
            Envelope,
        ):
            yield response

    async def receive_commands(self) -> AsyncGenerator[Command, None]:
        """Receive coordinator commands (feedback, visibility grants)."""

        request = ReceiveCommandsRequest()

        async for response in self._unary_stream(
            "/wacp.v1.AgentService/ReceiveCommands",
            request,
            Command,
        ):
            yield response


class HighwayServiceStub(betterproto.ServiceStub):
    """
    Highway-facing gRPC service. Multiple simultaneous human connections.
    """

    async def authenticate(self, *, auth_token: str = "") -> AuthenticateResponse:
        """Authenticate a human user."""

        request = AuthenticateRequest()
        request.auth_token = auth_token

        return await self._unary_unary(
            "/wacp.v1.HighwayService/Authenticate",
            request,
            AuthenticateResponse,
        )

    async def inject_envelope(
        self,
        *,
        to_workspace: str = "",
        type: str = "",
        payload: bytes = b"",
        priority: "EnvelopePriority" = 0,
        client_request_id: str = "",
    ) -> InjectEnvelopeResponse:
        """Inject an envelope into any workspace."""

        request = InjectEnvelopeRequest()
        request.to_workspace = to_workspace
        request.type = type
        request.payload = payload
        request.priority = priority
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.HighwayService/InjectEnvelope",
            request,
            InjectEnvelopeResponse,
        )

    async def respond_to_gate(
        self,
        *,
        gate_id: str = "",
        decision: "GateDecision" = 0,
        modifications: bytes = b"",
        client_request_id: str = "",
    ) -> GateResponseAck:
        """Respond to a gate event (approve, reject, modify)."""

        request = GateResponse()
        request.gate_id = gate_id
        request.decision = decision
        request.modifications = modifications
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.HighwayService/RespondToGate",
            request,
            GateResponseAck,
        )

    async def respond_to_escalation(
        self,
        *,
        escalation_id: str = "",
        feedback: Optional["Envelope"] = None,
        abort: bool = False,
        delegate_to_coordinator: bool = False,
        client_request_id: str = "",
    ) -> EscalationResponseAck:
        """Respond to an escalation."""

        request = EscalationResponse()
        request.escalation_id = escalation_id
        if feedback is not None:
            request.feedback = feedback
        request.abort = abort
        request.delegate_to_coordinator = delegate_to_coordinator
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.HighwayService/RespondToEscalation",
            request,
            EscalationResponseAck,
        )

    async def query_trail(
        self,
        *,
        workspace_id: str = "",
        event_type: str = "",
        actor: str = "",
        from_: Optional["Timestamp"] = None,
        to: Optional["Timestamp"] = None,
        limit: int = 0,
        client_request_id: str = "",
    ) -> QueryTrailResponse:
        """Query the global trail."""

        request = HighwayQueryTrailRequest()
        request.workspace_id = workspace_id
        request.event_type = event_type
        request.actor = actor
        if from_ is not None:
            request.from_ = from_
        if to is not None:
            request.to = to
        request.limit = limit
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.HighwayService/QueryTrail",
            request,
            QueryTrailResponse,
        )

    async def get_workspace(self, *, workspace_id: str = "") -> WorkspaceView:
        """Read a workspace's current state."""

        request = GetWorkspaceRequest()
        request.workspace_id = workspace_id

        return await self._unary_unary(
            "/wacp.v1.HighwayService/GetWorkspace",
            request,
            WorkspaceView,
        )

    async def get_task_graph(self) -> TaskGraphView:
        """Read the task graph."""

        request = GetTaskGraphRequest()

        return await self._unary_unary(
            "/wacp.v1.HighwayService/GetTaskGraph",
            request,
            TaskGraphView,
        )

    async def get_checkpoint(self, *, checkpoint_id: str = "") -> CheckpointView:
        """Read a checkpoint's payload."""

        request = GetCheckpointRequest()
        request.checkpoint_id = checkpoint_id

        return await self._unary_unary(
            "/wacp.v1.HighwayService/GetCheckpoint",
            request,
            CheckpointView,
        )

    async def stream_trail(
        self,
        *,
        workspace_id: str = "",
        event_type: str = "",
        from_beginning: bool = False,
    ) -> AsyncGenerator[TrailEntry, None]:
        """Stream trail entries in real time."""

        request = StreamTrailRequest()
        request.workspace_id = workspace_id
        request.event_type = event_type
        request.from_beginning = from_beginning

        async for response in self._unary_stream(
            "/wacp.v1.HighwayService/StreamTrail",
            request,
            TrailEntry,
        ):
            yield response

    async def stream_gates(self) -> AsyncGenerator[GateEvent, None]:
        """Stream gate events as they occur."""

        request = StreamGatesRequest()

        async for response in self._unary_stream(
            "/wacp.v1.HighwayService/StreamGates",
            request,
            GateEvent,
        ):
            yield response

    async def stream_escalations(
        self, *, user_id: str = ""
    ) -> AsyncGenerator[EscalationEvent, None]:
        """Stream escalation events."""

        request = StreamEscalationsRequest()
        request.user_id = user_id

        async for response in self._unary_stream(
            "/wacp.v1.HighwayService/StreamEscalations",
            request,
            EscalationEvent,
        ):
            yield response

    async def stream_workspace_changes(
        self, *, workspace_id: str = ""
    ) -> AsyncGenerator[WorkspaceStateChange, None]:
        """Stream workspace state changes."""

        request = StreamWorkspaceChangesRequest()
        request.workspace_id = workspace_id

        async for response in self._unary_stream(
            "/wacp.v1.HighwayService/StreamWorkspaceChanges",
            request,
            WorkspaceStateChange,
        ):
            yield response


class CoordinatorServiceStub(betterproto.ServiceStub):
    """
    Coordinator-facing gRPC service. For custom coordinators and local-sdk.
    """

    async def submit_goal(
        self,
        *,
        description: str = "",
        context: bytes = b"",
        client_request_id: str = "",
    ) -> SubmitGoalResponse:
        """Submit a top-level goal."""

        request = SubmitGoalRequest()
        request.description = description
        request.context = context
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/SubmitGoal",
            request,
            SubmitGoalResponse,
        )

    async def decompose(
        self, *, tasks: List["TaskDefinition"] = [], client_request_id: str = ""
    ) -> DecomposeResponse:
        """Create a task graph (DAG) from task definitions."""

        request = DecomposeRequest()
        if tasks is not None:
            request.tasks = tasks
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/Decompose",
            request,
            DecomposeResponse,
        )

    async def get_ready_tasks(
        self, *, client_request_id: str = ""
    ) -> GetReadyTasksResponse:
        """Get tasks ready for dispatch (all dependencies satisfied)."""

        request = GetReadyTasksRequest()
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/GetReadyTasks",
            request,
            GetReadyTasksResponse,
        )

    async def cancel_task(
        self, *, task_id: str = "", reason: str = "", client_request_id: str = ""
    ) -> CancelTaskResponse:
        """Cancel a task (cascades to dependents and assigned workspace)."""

        request = CancelTaskRequest()
        request.task_id = task_id
        request.reason = reason
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/CancelTask",
            request,
            CancelTaskResponse,
        )

    async def dispatch(
        self,
        *,
        task_id: str = "",
        role: str = "",
        directive_payload: bytes = b"",
        tools: List[str] = [],
        budget: Optional["ResourceBudget"] = None,
        client_request_id: str = "",
    ) -> DispatchResponse:
        """Create a workspace for a task."""

        request = DispatchRequest()
        request.task_id = task_id
        request.role = role
        request.directive_payload = directive_payload
        request.tools = tools
        if budget is not None:
            request.budget = budget
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/Dispatch",
            request,
            DispatchResponse,
        )

    async def abort_workspace(
        self, *, workspace_id: str = "", reason: str = "", client_request_id: str = ""
    ) -> AbortWorkspaceResponse:
        """Terminate a workspace."""

        request = AbortWorkspaceRequest()
        request.workspace_id = workspace_id
        request.reason = reason
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/AbortWorkspace",
            request,
            AbortWorkspaceResponse,
        )

    async def suspend_workspace(
        self, *, workspace_id: str = "", client_request_id: str = ""
    ) -> SuspendWorkspaceResponse:
        """Pause a workspace."""

        request = SuspendWorkspaceRequest()
        request.workspace_id = workspace_id
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/SuspendWorkspace",
            request,
            SuspendWorkspaceResponse,
        )

    async def resume_workspace(
        self, *, workspace_id: str = "", client_request_id: str = ""
    ) -> ResumeWorkspaceResponse:
        """Resume a paused workspace."""

        request = ResumeWorkspaceRequest()
        request.workspace_id = workspace_id
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/ResumeWorkspace",
            request,
            ResumeWorkspaceResponse,
        )

    async def send_directive(
        self,
        *,
        workspace_id: str = "",
        payload: bytes = b"",
        client_request_id: str = "",
    ) -> SendDirectiveResponse:
        """Send a directive envelope to a workspace."""

        request = SendDirectiveRequest()
        request.workspace_id = workspace_id
        request.payload = payload
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/SendDirective",
            request,
            SendDirectiveResponse,
        )

    async def send_feedback(
        self,
        *,
        workspace_id: str = "",
        payload: bytes = b"",
        in_reply_to: str = "",
        client_request_id: str = "",
    ) -> SendFeedbackResponse:
        """Send a feedback envelope to a workspace."""

        request = SendFeedbackRequest()
        request.workspace_id = workspace_id
        request.payload = payload
        request.in_reply_to = in_reply_to
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/SendFeedback",
            request,
            SendFeedbackResponse,
        )

    async def trigger_integration(
        self, *, workspace_id: str = "", client_request_id: str = ""
    ) -> TriggerIntegrationResponse:
        """Trigger the integration pipeline for a completed workspace."""

        request = TriggerIntegrationRequest()
        request.workspace_id = workspace_id
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/TriggerIntegration",
            request,
            TriggerIntegrationResponse,
        )

    async def get_allocatable(
        self, *, client_request_id: str = ""
    ) -> GetAllocatableResponse:
        """Get remaining allocatable budget."""

        request = GetAllocatableRequest()
        request.client_request_id = client_request_id

        return await self._unary_unary(
            "/wacp.v1.CoordinatorService/GetAllocatable",
            request,
            GetAllocatableResponse,
        )

    async def stream_signals(
        self, *, workspace_filter: str = "", signal_type_filter: str = ""
    ) -> AsyncGenerator[SignalEvent, None]:
        """Stream signals from child workspaces."""

        request = StreamSignalsRequest()
        request.workspace_filter = workspace_filter
        request.signal_type_filter = signal_type_filter

        async for response in self._unary_stream(
            "/wacp.v1.CoordinatorService/StreamSignals",
            request,
            SignalEvent,
        ):
            yield response
